#!/bin/bash

test -f /root/bootstrap && /root/bootstrap

echo "$VNC_PW" | vncpasswd -f >> /root/.vnc/passwd
vncserver -geometry $VNC_RES
/usr/share/novnc/utils/launch.sh --vnc localhost:5901 --listen 6901
